/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teamcromwellp2;

/**
 *
 * @author julesandsteve
 */
public class ConcertHall extends javax.swing.JFrame {

    /**
     * Creates new form ConcertHall
     */
    public ConcertHall() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblStage = new javax.swing.JLabel();
        lblFireExit1 = new javax.swing.JLabel();
        lblFireExit = new javax.swing.JLabel();
        lblGoldSeats = new javax.swing.JLabel();
        lblSilverSeats = new javax.swing.JLabel();
        lblBronzeSeats = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        lblD = new javax.swing.JLabel();
        lblE = new javax.swing.JLabel();
        lblF = new javax.swing.JLabel();
        lblG = new javax.swing.JLabel();
        lblH = new javax.swing.JLabel();
        lblI = new javax.swing.JLabel();
        lblMainEntrance = new javax.swing.JLabel();
        btnA5 = new javax.swing.JButton();
        btnA4 = new javax.swing.JButton();
        btnA3 = new javax.swing.JButton();
        btnA2 = new javax.swing.JButton();
        btnA1 = new javax.swing.JButton();
        btnB5 = new javax.swing.JButton();
        btnB4 = new javax.swing.JButton();
        btnB3 = new javax.swing.JButton();
        btnB2 = new javax.swing.JButton();
        btnB1 = new javax.swing.JButton();
        btnC5 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        btnC3 = new javax.swing.JButton();
        btnC2 = new javax.swing.JButton();
        btnC1 = new javax.swing.JButton();
        btnF1 = new javax.swing.JButton();
        btnD5 = new javax.swing.JButton();
        btnD4 = new javax.swing.JButton();
        btnD3 = new javax.swing.JButton();
        btnD2 = new javax.swing.JButton();
        btnD1 = new javax.swing.JButton();
        btnE5 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        btnE3 = new javax.swing.JButton();
        btnE2 = new javax.swing.JButton();
        btnE1 = new javax.swing.JButton();
        btnF5 = new javax.swing.JButton();
        btnF4 = new javax.swing.JButton();
        btnF3 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        btnI1 = new javax.swing.JButton();
        btnG5 = new javax.swing.JButton();
        btnG4 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        btnG2 = new javax.swing.JButton();
        btnG1 = new javax.swing.JButton();
        btnH5 = new javax.swing.JButton();
        btnH4 = new javax.swing.JButton();
        btnH3 = new javax.swing.JButton();
        btnH2 = new javax.swing.JButton();
        btnH1 = new javax.swing.JButton();
        btnI5 = new javax.swing.JButton();
        btnI4 = new javax.swing.JButton();
        btnI3 = new javax.swing.JButton();
        btnI2 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        btnA10 = new javax.swing.JButton();
        btnA9 = new javax.swing.JButton();
        btnA8 = new javax.swing.JButton();
        btnA7 = new javax.swing.JButton();
        btnA6 = new javax.swing.JButton();
        btnB10 = new javax.swing.JButton();
        btnB9 = new javax.swing.JButton();
        btnB8 = new javax.swing.JButton();
        btnB7 = new javax.swing.JButton();
        btnB6 = new javax.swing.JButton();
        btnC10 = new javax.swing.JButton();
        btnC9 = new javax.swing.JButton();
        btnC8 = new javax.swing.JButton();
        btnC7 = new javax.swing.JButton();
        btnF6 = new javax.swing.JButton();
        btnD10 = new javax.swing.JButton();
        btnD9 = new javax.swing.JButton();
        btnD8 = new javax.swing.JButton();
        btnD7 = new javax.swing.JButton();
        btnD6 = new javax.swing.JButton();
        btnE10 = new javax.swing.JButton();
        btnE9 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        btnE7 = new javax.swing.JButton();
        btnE6 = new javax.swing.JButton();
        btnF10 = new javax.swing.JButton();
        btnF9 = new javax.swing.JButton();
        btnF8 = new javax.swing.JButton();
        btnF7 = new javax.swing.JButton();
        btnI6 = new javax.swing.JButton();
        btnG10 = new javax.swing.JButton();
        btnG9 = new javax.swing.JButton();
        btnG8 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        btnG6 = new javax.swing.JButton();
        btnH10 = new javax.swing.JButton();
        btnH9 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        btnH7 = new javax.swing.JButton();
        jButton101 = new javax.swing.JButton();
        btnI10 = new javax.swing.JButton();
        btnI9 = new javax.swing.JButton();
        btnI8 = new javax.swing.JButton();
        btnI7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(205, 125, 50));
        jPanel1.setToolTipText("");

        lblStage.setText("Stage");

        lblFireExit1.setFont(new java.awt.Font("Ubuntu", 0, 8)); // NOI18N
        lblFireExit1.setText("Fire exit");

        lblFireExit.setFont(new java.awt.Font("Ubuntu", 0, 8)); // NOI18N
        lblFireExit.setText("Fire exit");

        lblGoldSeats.setText("Gold Seats");

        lblSilverSeats.setText("Silver Seats");

        lblBronzeSeats.setText("Bronze Seats");

        lbl10.setText("10");

        lbl9.setText("9");

        lbl8.setText("8");

        lbl7.setText("7");

        lbl6.setText("6");

        lbl5.setText("5");

        lbl4.setText("4");

        lbl3.setText("3");

        lbl2.setText("2");

        lbl1.setText("1");

        lblB.setText("B");

        lblA.setText("A");

        lblC.setText("C");

        lblD.setText("D");

        lblE.setText("E");

        lblF.setText("F");

        lblG.setText("G");

        lblH.setText("H");

        lblI.setText("I");

        lblMainEntrance.setText("Main Entrance");

        btnA5.setBackground(new java.awt.Color(255, 215, 0));
        btnA5.setForeground(new java.awt.Color(255, 215, 0));
        btnA5.setToolTipText("");
        btnA5.setMaximumSize(new java.awt.Dimension(72, 20));

        btnA4.setBackground(new java.awt.Color(255, 215, 0));
        btnA4.setForeground(new java.awt.Color(255, 215, 0));
        btnA4.setToolTipText("");
        btnA4.setMaximumSize(new java.awt.Dimension(72, 20));

        btnA3.setBackground(new java.awt.Color(255, 215, 0));
        btnA3.setForeground(new java.awt.Color(255, 215, 0));
        btnA3.setToolTipText("");
        btnA3.setMaximumSize(new java.awt.Dimension(72, 20));

        btnA2.setBackground(new java.awt.Color(255, 215, 0));
        btnA2.setForeground(new java.awt.Color(255, 215, 0));
        btnA2.setToolTipText("");
        btnA2.setMaximumSize(new java.awt.Dimension(72, 20));
        btnA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA2ActionPerformed(evt);
            }
        });

        btnA1.setBackground(new java.awt.Color(255, 215, 0));
        btnA1.setForeground(new java.awt.Color(255, 215, 0));
        btnA1.setToolTipText("");
        btnA1.setMaximumSize(new java.awt.Dimension(72, 20));
        btnA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA1ActionPerformed(evt);
            }
        });

        btnB5.setBackground(new java.awt.Color(255, 215, 0));
        btnB5.setForeground(new java.awt.Color(255, 215, 0));
        btnB5.setToolTipText("");
        btnB5.setMaximumSize(new java.awt.Dimension(72, 20));

        btnB4.setBackground(new java.awt.Color(255, 215, 0));
        btnB4.setForeground(new java.awt.Color(255, 215, 0));
        btnB4.setToolTipText("");
        btnB4.setMaximumSize(new java.awt.Dimension(72, 20));

        btnB3.setBackground(new java.awt.Color(255, 215, 0));
        btnB3.setForeground(new java.awt.Color(255, 215, 0));
        btnB3.setToolTipText("");
        btnB3.setMaximumSize(new java.awt.Dimension(72, 20));

        btnB2.setBackground(new java.awt.Color(255, 215, 0));
        btnB2.setForeground(new java.awt.Color(255, 215, 0));
        btnB2.setToolTipText("");
        btnB2.setMaximumSize(new java.awt.Dimension(72, 20));

        btnB1.setBackground(new java.awt.Color(255, 215, 0));
        btnB1.setForeground(new java.awt.Color(255, 215, 0));
        btnB1.setToolTipText("");
        btnB1.setMaximumSize(new java.awt.Dimension(72, 20));

        btnC5.setBackground(new java.awt.Color(255, 215, 0));
        btnC5.setForeground(new java.awt.Color(255, 215, 0));
        btnC5.setToolTipText("");
        btnC5.setMaximumSize(new java.awt.Dimension(72, 20));

        jButton12.setBackground(new java.awt.Color(255, 215, 0));
        jButton12.setForeground(new java.awt.Color(255, 215, 0));
        jButton12.setToolTipText("");
        jButton12.setMaximumSize(new java.awt.Dimension(72, 20));

        btnC3.setBackground(new java.awt.Color(255, 215, 0));
        btnC3.setForeground(new java.awt.Color(255, 215, 0));
        btnC3.setToolTipText("");
        btnC3.setMaximumSize(new java.awt.Dimension(72, 20));

        btnC2.setBackground(new java.awt.Color(255, 215, 0));
        btnC2.setForeground(new java.awt.Color(255, 215, 0));
        btnC2.setToolTipText("");
        btnC2.setMaximumSize(new java.awt.Dimension(72, 20));

        btnC1.setBackground(new java.awt.Color(255, 215, 0));
        btnC1.setForeground(new java.awt.Color(255, 215, 0));
        btnC1.setToolTipText("");
        btnC1.setMaximumSize(new java.awt.Dimension(72, 20));

        btnF1.setBackground(new java.awt.Color(192, 192, 192));
        btnF1.setForeground(new java.awt.Color(192, 192, 192));
        btnF1.setMaximumSize(new java.awt.Dimension(72, 20));

        btnD5.setBackground(new java.awt.Color(192, 192, 192));
        btnD5.setForeground(new java.awt.Color(192, 192, 192));
        btnD5.setMaximumSize(new java.awt.Dimension(72, 20));

        btnD4.setBackground(new java.awt.Color(192, 192, 192));
        btnD4.setForeground(new java.awt.Color(192, 192, 192));
        btnD4.setMaximumSize(new java.awt.Dimension(72, 20));

        btnD3.setBackground(new java.awt.Color(192, 192, 192));
        btnD3.setForeground(new java.awt.Color(192, 192, 192));
        btnD3.setMaximumSize(new java.awt.Dimension(72, 20));

        btnD2.setBackground(new java.awt.Color(192, 192, 192));
        btnD2.setForeground(new java.awt.Color(192, 192, 192));
        btnD2.setMaximumSize(new java.awt.Dimension(72, 20));

        btnD1.setBackground(new java.awt.Color(192, 192, 192));
        btnD1.setForeground(new java.awt.Color(192, 192, 192));
        btnD1.setMaximumSize(new java.awt.Dimension(72, 20));

        btnE5.setBackground(new java.awt.Color(192, 192, 192));
        btnE5.setForeground(new java.awt.Color(192, 192, 192));
        btnE5.setMaximumSize(new java.awt.Dimension(72, 20));

        jButton38.setBackground(new java.awt.Color(192, 192, 192));
        jButton38.setForeground(new java.awt.Color(192, 192, 192));
        jButton38.setMaximumSize(new java.awt.Dimension(72, 20));

        btnE3.setBackground(new java.awt.Color(192, 192, 192));
        btnE3.setForeground(new java.awt.Color(192, 192, 192));
        btnE3.setMaximumSize(new java.awt.Dimension(72, 20));

        btnE2.setBackground(new java.awt.Color(192, 192, 192));
        btnE2.setForeground(new java.awt.Color(192, 192, 192));
        btnE2.setMaximumSize(new java.awt.Dimension(72, 20));

        btnE1.setBackground(new java.awt.Color(192, 192, 192));
        btnE1.setForeground(new java.awt.Color(192, 192, 192));
        btnE1.setMaximumSize(new java.awt.Dimension(72, 20));

        btnF5.setBackground(new java.awt.Color(192, 192, 192));
        btnF5.setForeground(new java.awt.Color(192, 192, 192));
        btnF5.setMaximumSize(new java.awt.Dimension(72, 20));

        btnF4.setBackground(new java.awt.Color(192, 192, 192));
        btnF4.setForeground(new java.awt.Color(192, 192, 192));
        btnF4.setMaximumSize(new java.awt.Dimension(72, 20));

        btnF3.setBackground(new java.awt.Color(192, 192, 192));
        btnF3.setForeground(new java.awt.Color(192, 192, 192));
        btnF3.setMaximumSize(new java.awt.Dimension(72, 20));

        jButton45.setBackground(new java.awt.Color(192, 192, 192));
        jButton45.setForeground(new java.awt.Color(192, 192, 192));
        jButton45.setMaximumSize(new java.awt.Dimension(72, 20));

        btnI1.setBackground(new java.awt.Color(205, 125, 50));
        btnI1.setForeground(new java.awt.Color(205, 125, 50));
        btnI1.setMaximumSize(new java.awt.Dimension(72, 20));

        btnG5.setBackground(new java.awt.Color(205, 125, 50));
        btnG5.setForeground(new java.awt.Color(205, 125, 50));
        btnG5.setMaximumSize(new java.awt.Dimension(72, 20));

        btnG4.setBackground(new java.awt.Color(205, 125, 50));
        btnG4.setForeground(new java.awt.Color(205, 125, 50));
        btnG4.setMaximumSize(new java.awt.Dimension(72, 20));

        jButton49.setBackground(new java.awt.Color(205, 125, 50));
        jButton49.setForeground(new java.awt.Color(205, 125, 50));
        jButton49.setMaximumSize(new java.awt.Dimension(72, 20));

        btnG2.setBackground(new java.awt.Color(205, 125, 50));
        btnG2.setForeground(new java.awt.Color(205, 125, 50));
        btnG2.setMaximumSize(new java.awt.Dimension(72, 20));

        btnG1.setBackground(new java.awt.Color(205, 125, 50));
        btnG1.setForeground(new java.awt.Color(205, 125, 50));
        btnG1.setMaximumSize(new java.awt.Dimension(72, 20));

        btnH5.setBackground(new java.awt.Color(205, 125, 50));
        btnH5.setForeground(new java.awt.Color(205, 125, 50));
        btnH5.setMaximumSize(new java.awt.Dimension(72, 20));

        btnH4.setBackground(new java.awt.Color(205, 125, 50));
        btnH4.setForeground(new java.awt.Color(205, 125, 50));
        btnH4.setMaximumSize(new java.awt.Dimension(72, 20));

        btnH3.setBackground(new java.awt.Color(205, 125, 50));
        btnH3.setForeground(new java.awt.Color(205, 125, 50));
        btnH3.setMaximumSize(new java.awt.Dimension(72, 20));

        btnH2.setBackground(new java.awt.Color(205, 125, 50));
        btnH2.setForeground(new java.awt.Color(205, 125, 50));
        btnH2.setMaximumSize(new java.awt.Dimension(72, 20));

        btnH1.setBackground(new java.awt.Color(205, 125, 50));
        btnH1.setForeground(new java.awt.Color(205, 125, 50));
        btnH1.setMaximumSize(new java.awt.Dimension(72, 20));

        btnI5.setBackground(new java.awt.Color(205, 125, 50));
        btnI5.setForeground(new java.awt.Color(205, 125, 50));
        btnI5.setMaximumSize(new java.awt.Dimension(72, 20));

        btnI4.setBackground(new java.awt.Color(205, 125, 50));
        btnI4.setForeground(new java.awt.Color(205, 125, 50));
        btnI4.setMaximumSize(new java.awt.Dimension(72, 20));

        btnI3.setBackground(new java.awt.Color(205, 125, 50));
        btnI3.setForeground(new java.awt.Color(205, 125, 50));
        btnI3.setMaximumSize(new java.awt.Dimension(72, 20));

        btnI2.setBackground(new java.awt.Color(205, 125, 50));
        btnI2.setForeground(new java.awt.Color(205, 125, 50));
        btnI2.setMaximumSize(new java.awt.Dimension(72, 20));

        jButton61.setBackground(new java.awt.Color(255, 215, 0));
        jButton61.setForeground(new java.awt.Color(255, 215, 0));
        jButton61.setToolTipText("");
        jButton61.setMaximumSize(new java.awt.Dimension(72, 20));

        btnA10.setBackground(new java.awt.Color(255, 215, 0));
        btnA10.setForeground(new java.awt.Color(255, 215, 0));
        btnA10.setToolTipText("");
        btnA10.setMaximumSize(new java.awt.Dimension(72, 20));
        btnA10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA10ActionPerformed(evt);
            }
        });

        btnA9.setBackground(new java.awt.Color(255, 215, 0));
        btnA9.setForeground(new java.awt.Color(255, 215, 0));
        btnA9.setToolTipText("");
        btnA9.setMaximumSize(new java.awt.Dimension(72, 20));

        btnA8.setBackground(new java.awt.Color(255, 215, 0));
        btnA8.setForeground(new java.awt.Color(255, 215, 0));
        btnA8.setToolTipText("");
        btnA8.setMaximumSize(new java.awt.Dimension(72, 20));

        btnA7.setBackground(new java.awt.Color(255, 215, 0));
        btnA7.setForeground(new java.awt.Color(255, 215, 0));
        btnA7.setToolTipText("");
        btnA7.setMaximumSize(new java.awt.Dimension(72, 20));

        btnA6.setBackground(new java.awt.Color(255, 215, 0));
        btnA6.setForeground(new java.awt.Color(255, 215, 0));
        btnA6.setToolTipText("");
        btnA6.setMaximumSize(new java.awt.Dimension(72, 20));

        btnB10.setBackground(new java.awt.Color(255, 215, 0));
        btnB10.setForeground(new java.awt.Color(255, 215, 0));
        btnB10.setToolTipText("");
        btnB10.setMaximumSize(new java.awt.Dimension(72, 20));

        btnB9.setBackground(new java.awt.Color(255, 215, 0));
        btnB9.setForeground(new java.awt.Color(255, 215, 0));
        btnB9.setToolTipText("");
        btnB9.setMaximumSize(new java.awt.Dimension(72, 20));

        btnB8.setBackground(new java.awt.Color(255, 215, 0));
        btnB8.setForeground(new java.awt.Color(255, 215, 0));
        btnB8.setToolTipText("");
        btnB8.setMaximumSize(new java.awt.Dimension(72, 20));

        btnB7.setBackground(new java.awt.Color(255, 215, 0));
        btnB7.setForeground(new java.awt.Color(255, 215, 0));
        btnB7.setToolTipText("");
        btnB7.setMaximumSize(new java.awt.Dimension(72, 20));

        btnB6.setBackground(new java.awt.Color(255, 215, 0));
        btnB6.setForeground(new java.awt.Color(255, 215, 0));
        btnB6.setToolTipText("");
        btnB6.setMaximumSize(new java.awt.Dimension(72, 20));

        btnC10.setBackground(new java.awt.Color(255, 215, 0));
        btnC10.setForeground(new java.awt.Color(255, 215, 0));
        btnC10.setToolTipText("");
        btnC10.setMaximumSize(new java.awt.Dimension(72, 20));

        btnC9.setBackground(new java.awt.Color(255, 215, 0));
        btnC9.setForeground(new java.awt.Color(255, 215, 0));
        btnC9.setToolTipText("");
        btnC9.setMaximumSize(new java.awt.Dimension(72, 20));

        btnC8.setBackground(new java.awt.Color(255, 215, 0));
        btnC8.setForeground(new java.awt.Color(255, 215, 0));
        btnC8.setToolTipText("");
        btnC8.setMaximumSize(new java.awt.Dimension(72, 20));

        btnC7.setBackground(new java.awt.Color(255, 215, 0));
        btnC7.setForeground(new java.awt.Color(255, 215, 0));
        btnC7.setToolTipText("");
        btnC7.setMaximumSize(new java.awt.Dimension(72, 20));

        btnF6.setBackground(new java.awt.Color(192, 192, 192));
        btnF6.setForeground(new java.awt.Color(192, 192, 192));
        btnF6.setMaximumSize(new java.awt.Dimension(72, 20));

        btnD10.setBackground(new java.awt.Color(192, 192, 192));
        btnD10.setForeground(new java.awt.Color(192, 192, 192));
        btnD10.setMaximumSize(new java.awt.Dimension(72, 20));

        btnD9.setBackground(new java.awt.Color(192, 192, 192));
        btnD9.setForeground(new java.awt.Color(192, 192, 192));
        btnD9.setMaximumSize(new java.awt.Dimension(72, 20));

        btnD8.setBackground(new java.awt.Color(192, 192, 192));
        btnD8.setForeground(new java.awt.Color(192, 192, 192));
        btnD8.setMaximumSize(new java.awt.Dimension(72, 20));

        btnD7.setBackground(new java.awt.Color(192, 192, 192));
        btnD7.setForeground(new java.awt.Color(192, 192, 192));
        btnD7.setMaximumSize(new java.awt.Dimension(72, 20));

        btnD6.setBackground(new java.awt.Color(192, 192, 192));
        btnD6.setForeground(new java.awt.Color(192, 192, 192));
        btnD6.setMaximumSize(new java.awt.Dimension(72, 20));

        btnE10.setBackground(new java.awt.Color(192, 192, 192));
        btnE10.setForeground(new java.awt.Color(192, 192, 192));
        btnE10.setMaximumSize(new java.awt.Dimension(72, 20));

        btnE9.setBackground(new java.awt.Color(192, 192, 192));
        btnE9.setForeground(new java.awt.Color(192, 192, 192));
        btnE9.setMaximumSize(new java.awt.Dimension(72, 20));

        jButton84.setBackground(new java.awt.Color(192, 192, 192));
        jButton84.setForeground(new java.awt.Color(192, 192, 192));
        jButton84.setMaximumSize(new java.awt.Dimension(72, 20));

        btnE7.setBackground(new java.awt.Color(192, 192, 192));
        btnE7.setForeground(new java.awt.Color(192, 192, 192));
        btnE7.setMaximumSize(new java.awt.Dimension(72, 20));

        btnE6.setBackground(new java.awt.Color(192, 192, 192));
        btnE6.setForeground(new java.awt.Color(192, 192, 192));
        btnE6.setMaximumSize(new java.awt.Dimension(72, 20));

        btnF10.setBackground(new java.awt.Color(192, 192, 192));
        btnF10.setForeground(new java.awt.Color(192, 192, 192));
        btnF10.setMaximumSize(new java.awt.Dimension(72, 20));

        btnF9.setBackground(new java.awt.Color(192, 192, 192));
        btnF9.setForeground(new java.awt.Color(192, 192, 192));
        btnF9.setMaximumSize(new java.awt.Dimension(72, 20));

        btnF8.setBackground(new java.awt.Color(192, 192, 192));
        btnF8.setForeground(new java.awt.Color(192, 192, 192));
        btnF8.setMaximumSize(new java.awt.Dimension(72, 20));

        btnF7.setBackground(new java.awt.Color(192, 192, 192));
        btnF7.setForeground(new java.awt.Color(192, 192, 192));
        btnF7.setMaximumSize(new java.awt.Dimension(72, 20));

        btnI6.setBackground(new java.awt.Color(205, 125, 50));
        btnI6.setForeground(new java.awt.Color(205, 125, 50));
        btnI6.setMaximumSize(new java.awt.Dimension(72, 20));

        btnG10.setBackground(new java.awt.Color(205, 125, 50));
        btnG10.setForeground(new java.awt.Color(205, 125, 50));
        btnG10.setMaximumSize(new java.awt.Dimension(72, 20));

        btnG9.setBackground(new java.awt.Color(205, 125, 50));
        btnG9.setForeground(new java.awt.Color(205, 125, 50));
        btnG9.setMaximumSize(new java.awt.Dimension(72, 20));

        btnG8.setBackground(new java.awt.Color(205, 125, 50));
        btnG8.setForeground(new java.awt.Color(205, 125, 50));
        btnG8.setMaximumSize(new java.awt.Dimension(72, 20));

        jButton95.setBackground(new java.awt.Color(205, 125, 50));
        jButton95.setForeground(new java.awt.Color(205, 125, 50));
        jButton95.setMaximumSize(new java.awt.Dimension(72, 20));
        jButton95.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton95ActionPerformed(evt);
            }
        });

        btnG6.setBackground(new java.awt.Color(205, 125, 50));
        btnG6.setForeground(new java.awt.Color(205, 125, 50));
        btnG6.setMaximumSize(new java.awt.Dimension(72, 20));

        btnH10.setBackground(new java.awt.Color(205, 125, 50));
        btnH10.setForeground(new java.awt.Color(205, 125, 50));
        btnH10.setMaximumSize(new java.awt.Dimension(72, 20));

        btnH9.setBackground(new java.awt.Color(205, 125, 50));
        btnH9.setForeground(new java.awt.Color(205, 125, 50));
        btnH9.setMaximumSize(new java.awt.Dimension(72, 20));

        jButton99.setBackground(new java.awt.Color(205, 125, 50));
        jButton99.setForeground(new java.awt.Color(205, 125, 50));
        jButton99.setMaximumSize(new java.awt.Dimension(72, 20));

        btnH7.setBackground(new java.awt.Color(205, 125, 50));
        btnH7.setForeground(new java.awt.Color(205, 125, 50));
        btnH7.setMaximumSize(new java.awt.Dimension(72, 20));

        jButton101.setBackground(new java.awt.Color(205, 125, 50));
        jButton101.setForeground(new java.awt.Color(205, 125, 50));
        jButton101.setMaximumSize(new java.awt.Dimension(72, 20));

        btnI10.setBackground(new java.awt.Color(205, 125, 50));
        btnI10.setForeground(new java.awt.Color(205, 125, 50));
        btnI10.setMaximumSize(new java.awt.Dimension(72, 20));

        btnI9.setBackground(new java.awt.Color(205, 125, 50));
        btnI9.setForeground(new java.awt.Color(205, 125, 50));
        btnI9.setMaximumSize(new java.awt.Dimension(72, 20));

        btnI8.setBackground(new java.awt.Color(205, 125, 50));
        btnI8.setForeground(new java.awt.Color(205, 125, 50));
        btnI8.setMaximumSize(new java.awt.Dimension(72, 20));

        btnI7.setBackground(new java.awt.Color(205, 125, 50));
        btnI7.setForeground(new java.awt.Color(205, 125, 50));
        btnI7.setMaximumSize(new java.awt.Dimension(72, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFireExit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204)
                        .addComponent(lblStage))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblGoldSeats)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl10)
                                .addGap(18, 18, 18)
                                .addComponent(lbl9)
                                .addGap(18, 18, 18)
                                .addComponent(lbl8)
                                .addGap(18, 18, 18)
                                .addComponent(lbl7)
                                .addGap(38, 38, 38))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnA10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnA9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnA8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnA7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnA6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnB10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnB9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnB8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnB7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnB6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnC10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnC9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnC8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnC7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton61, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnD10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnD9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnD8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnD7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnD6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnE10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton84, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnF10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnF9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnF8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnF7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnF6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSilverSeats)
                            .addComponent(lblBronzeSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnG10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnG9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnG8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton95, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnG6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnH10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnH9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton99, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnH7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton101, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnI10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnI9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnI8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnI7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnI6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblFireExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblI)
                        .addComponent(lblG)
                        .addComponent(lblH))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblF)
                            .addComponent(lblD)
                            .addComponent(lblE))
                        .addGap(29, 29, 29)))
                .addGap(44, 44, 44))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMainEntrance)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl6)
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl5)
                                .addGap(24, 24, 24)
                                .addComponent(lbl4)
                                .addGap(18, 18, 18)
                                .addComponent(lbl3)
                                .addGap(18, 18, 18)
                                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnA5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnA4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnA3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnA2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnA1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnB5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnB4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnB3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnB2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnB1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnD5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnD4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnD3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnD2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnD1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnE5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnF5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnF4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnF3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnF1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnC5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnC3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnC2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnC1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnG5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnG4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton49, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnG2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnG1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnH5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnH4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnH3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnH2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnH1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnI5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnI4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnI3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnI2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnI1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblC)
                    .addComponent(lblA)
                    .addComponent(lblB))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFireExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFireExit, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblStage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl10)
                    .addComponent(lbl9)
                    .addComponent(lbl6)
                    .addComponent(lbl5)
                    .addComponent(lbl4)
                    .addComponent(lbl3)
                    .addComponent(lbl2)
                    .addComponent(lbl1)
                    .addComponent(lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lblGoldSeats))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnA10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnA9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnA8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnA7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnA6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnB10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnB9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnB8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnB7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnB6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnC10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnC9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnC8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnC7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton61, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(lblSilverSeats))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnD10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnD9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnD8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnD7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnD6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnE10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnE9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton84, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnE7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnE6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnF10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnF9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnF8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnF7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnF6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(59, 59, 59)
                        .addComponent(lblBronzeSeats)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMainEntrance)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnA5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnA4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnA3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnA2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnA1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnB5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnB4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnB3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnB2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnB1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnC5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnC3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnC2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnC1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblA)
                                .addGap(9, 9, 9)
                                .addComponent(lblB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblC)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnD5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnD4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnD3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnD2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnD1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnE5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnE3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnE2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnE1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnF5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnF4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnF3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnF1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblF)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnG10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnG9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnG8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton95, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnG6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnH10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnH9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton99, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnH7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton101, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnI10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnI9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnI8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnI7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnI6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnG5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnG4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton49, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnG2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnG1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnH5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnH4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnH3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnH2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnH1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnI5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnI4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnI3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnI2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnI1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblG)
                                .addGap(18, 18, 18)
                                .addComponent(lblH)
                                .addGap(18, 18, 18)
                                .addComponent(lblI)))
                        .addContainerGap(112, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA1ActionPerformed

    private void btnA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA2ActionPerformed

    private void btnA10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA10ActionPerformed

    private void jButton95ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton95ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton95ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConcertHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConcertHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConcertHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConcertHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConcertHall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA1;
    private javax.swing.JButton btnA10;
    private javax.swing.JButton btnA2;
    private javax.swing.JButton btnA3;
    private javax.swing.JButton btnA4;
    private javax.swing.JButton btnA5;
    private javax.swing.JButton btnA6;
    private javax.swing.JButton btnA7;
    private javax.swing.JButton btnA8;
    private javax.swing.JButton btnA9;
    private javax.swing.JButton btnB1;
    private javax.swing.JButton btnB10;
    private javax.swing.JButton btnB2;
    private javax.swing.JButton btnB3;
    private javax.swing.JButton btnB4;
    private javax.swing.JButton btnB5;
    private javax.swing.JButton btnB6;
    private javax.swing.JButton btnB7;
    private javax.swing.JButton btnB8;
    private javax.swing.JButton btnB9;
    private javax.swing.JButton btnC1;
    private javax.swing.JButton btnC10;
    private javax.swing.JButton btnC2;
    private javax.swing.JButton btnC3;
    private javax.swing.JButton btnC5;
    private javax.swing.JButton btnC7;
    private javax.swing.JButton btnC8;
    private javax.swing.JButton btnC9;
    private javax.swing.JButton btnD1;
    private javax.swing.JButton btnD10;
    private javax.swing.JButton btnD2;
    private javax.swing.JButton btnD3;
    private javax.swing.JButton btnD4;
    private javax.swing.JButton btnD5;
    private javax.swing.JButton btnD6;
    private javax.swing.JButton btnD7;
    private javax.swing.JButton btnD8;
    private javax.swing.JButton btnD9;
    private javax.swing.JButton btnE1;
    private javax.swing.JButton btnE10;
    private javax.swing.JButton btnE2;
    private javax.swing.JButton btnE3;
    private javax.swing.JButton btnE5;
    private javax.swing.JButton btnE6;
    private javax.swing.JButton btnE7;
    private javax.swing.JButton btnE9;
    private javax.swing.JButton btnF1;
    private javax.swing.JButton btnF10;
    private javax.swing.JButton btnF3;
    private javax.swing.JButton btnF4;
    private javax.swing.JButton btnF5;
    private javax.swing.JButton btnF6;
    private javax.swing.JButton btnF7;
    private javax.swing.JButton btnF8;
    private javax.swing.JButton btnF9;
    private javax.swing.JButton btnG1;
    private javax.swing.JButton btnG10;
    private javax.swing.JButton btnG2;
    private javax.swing.JButton btnG4;
    private javax.swing.JButton btnG5;
    private javax.swing.JButton btnG6;
    private javax.swing.JButton btnG8;
    private javax.swing.JButton btnG9;
    private javax.swing.JButton btnH1;
    private javax.swing.JButton btnH10;
    private javax.swing.JButton btnH2;
    private javax.swing.JButton btnH3;
    private javax.swing.JButton btnH4;
    private javax.swing.JButton btnH5;
    private javax.swing.JButton btnH7;
    private javax.swing.JButton btnH9;
    private javax.swing.JButton btnI1;
    private javax.swing.JButton btnI10;
    private javax.swing.JButton btnI2;
    private javax.swing.JButton btnI3;
    private javax.swing.JButton btnI4;
    private javax.swing.JButton btnI5;
    private javax.swing.JButton btnI6;
    private javax.swing.JButton btnI7;
    private javax.swing.JButton btnI8;
    private javax.swing.JButton btnI9;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblBronzeSeats;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblD;
    private javax.swing.JLabel lblE;
    private javax.swing.JLabel lblF;
    private javax.swing.JLabel lblFireExit;
    private javax.swing.JLabel lblFireExit1;
    private javax.swing.JLabel lblG;
    private javax.swing.JLabel lblGoldSeats;
    private javax.swing.JLabel lblH;
    private javax.swing.JLabel lblI;
    private javax.swing.JLabel lblMainEntrance;
    private javax.swing.JLabel lblSilverSeats;
    private javax.swing.JLabel lblStage;
    // End of variables declaration//GEN-END:variables
}
